import React, { useCallback, useEffect, useMemo, useRef, useState } from "react";
import {
  Activity, ArrowRight, Bell, CaretRight, ChartBar, CheckCircle, CloudArrowUp,
  Cube, Gear, ImageSquare, List, MagnifyingGlass, Moon, Package, PencilSimple,
  Plus, Receipt, ShieldCheck, ShoppingCart, SignOut, SpinnerGap, SquaresFour,
  Storefront, Sun, Tag, Trash, TrendUp, Truck, UserCircle, UsersThree, Warning, X,
} from "@phosphor-icons/react";
import { MediaManager } from "./MediaManager.jsx";
import { apiRequest, formatDate, money, readStorage, writeStorage } from "../shared/client.js";

const NAV = [
  ["overview", SquaresFour, "Overview"], ["orders", Package, "Orders"],
  ["products", ShoppingCart, "Products"], ["inventory", Cube, "Inventory"],
  ["customers", UsersThree, "Customers"], ["promotions", Tag, "Promotions"],
  ["media", ImageSquare, "Media"], ["settings", Gear, "Settings"],
];
const EMPTY_PRODUCT = { sku:"",name:"",category:"",subcategory:"",brand:"",description:"",price:"",oldPrice:"",currency:"BDT",stock:"0",availability:"in_stock",image:"",sourceName:"",sourceUrl:"",active:true,featured:false };
const EMPTY_COUPON = { code:"",discountType:"percent",discountValue:"10",minimumOrder:"0",usageLimit:"",startsAt:"",expiresAt:"",active:true };

function useEscape(callback, active) { useEffect(() => { if (!active) return undefined; const fn = (event) => event.key === "Escape" && callback(); addEventListener("keydown", fn); return () => removeEventListener("keydown", fn); }, [active, callback]); }
function Button({ children, variant="primary", className="", ...props }) { return <button className={`adm-button ${variant} ${className}`} {...props}>{children}</button>; }
function IconButton({ label, children, ...props }) { return <button className="adm-icon-button" aria-label={label} title={label} {...props}>{children}</button>; }
function Status({ value }) { return <span className={`adm-status ${String(value||"unknown").toLowerCase()}`}>{String(value||"unknown").replaceAll("_"," ")}</span>; }
function Loading({ label="Loading workspace" }) { return <div className="adm-loading" role="status"><SpinnerGap className="spin"/><strong>{label}</strong></div>; }
function Empty({ icon:Icon=Package,title,text,action }) { return <div className="adm-empty"><Icon weight="duotone"/><h3>{title}</h3><p>{text}</p>{action}</div>; }
function Drawer({ open,title,onClose,children,wide=false }) { const ref=useRef(null); useEscape(onClose,open); useEffect(()=>{if(!open)return undefined;const previous=document.activeElement;document.body.classList.add("adm-lock");setTimeout(()=>ref.current?.focus(),0);return()=>{document.body.classList.remove("adm-lock");previous?.focus?.();};},[open]); if(!open)return null; return <div className="adm-drawer-layer"><button className="adm-backdrop" aria-label={`Close ${title}`} onClick={onClose}/><aside ref={ref} tabIndex="-1" role="dialog" aria-modal="true" aria-label={title} className={`adm-drawer ${wide?"wide":""}`}><header><h2>{title}</h2><IconButton label={`Close ${title}`} onClick={onClose}><X/></IconButton></header>{children}</aside></div>; }
function Toasts({ items,dismiss }) { return <div className="adm-toasts" aria-live="polite">{items.map(item=><div key={item.id} className={item.tone}><span>{item.tone==="error"?<Warning weight="fill"/>:<CheckCircle weight="fill"/>}{item.message}</span><button aria-label="Dismiss notification" onClick={()=>dismiss(item.id)}><X/></button></div>)}</div>; }

function Login({ onLogin }) {
  const [form,setForm]=useState({email:"",password:""}); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  const submit=async(event)=>{event.preventDefault();setBusy(true);setError("");try{const response=await apiRequest("/api/admin/auth/login",{method:"POST",body:form});onLogin(response.user);}catch(requestError){setError(requestError.message);}finally{setBusy(false);}};
  return <main className="adm-login"><section><div className="adm-brand"><img src="/assets/bj-logo.png" alt="BJ Electronics"/><span><strong>BJ ELECTRONICS</strong><small>Administrator workspace</small></span></div><div><ShieldCheck weight="duotone"/><span>Protected operations portal</span><h1>Manage the entire store from one focused workspace.</h1><p>Orders, inventory, customers, promotions, media and platform health are organized for fast, secure daily operations.</p></div><small>© 2026 BJ Electronics · Authorized access only.</small></section><form onSubmit={submit}><span>Administrator access</span><h2>Sign in securely</h2><p>Use the administrator account configured in the production environment.</p><label>Email address<input required type="email" autoComplete="username" value={form.email} onChange={event=>setForm({...form,email:event.target.value})}/></label><label>Password<input required type="password" minLength="8" autoComplete="current-password" value={form.password} onChange={event=>setForm({...form,password:event.target.value})}/></label>{error&&<div className="adm-form-error"><Warning weight="fill"/>{error}</div>}<Button disabled={busy}>{busy?"Verifying…":"Sign in to Admin"}<ArrowRight/></Button><a href="/">Return to storefront</a></form></main>;
}

function ProductForm({ value,onChange,onSubmit,busy }) { return <form className="adm-form" onSubmit={onSubmit}><div className="adm-form-grid"><label>SKU<input required value={value.sku} onChange={e=>onChange({...value,sku:e.target.value})}/></label><label>Product name<input required value={value.name} onChange={e=>onChange({...value,name:e.target.value})}/></label><label>Category<input required value={value.category} onChange={e=>onChange({...value,category:e.target.value})}/></label><label>Subcategory<input value={value.subcategory||""} onChange={e=>onChange({...value,subcategory:e.target.value})}/></label><label>Brand<input value={value.brand||""} onChange={e=>onChange({...value,brand:e.target.value})}/></label><label>Availability<select value={value.availability} onChange={e=>onChange({...value,availability:e.target.value})}><option value="in_stock">In stock</option><option value="preorder">Preorder</option></select></label><label>Price (BDT)<input required type="number" min="1" value={value.price} onChange={e=>onChange({...value,price:e.target.value})}/></label><label>Old price<input type="number" min="1" value={value.oldPrice||""} onChange={e=>onChange({...value,oldPrice:e.target.value})}/></label><label>Stock<input required type="number" min="0" value={value.stock} onChange={e=>onChange({...value,stock:e.target.value})}/></label><label>Image URL<input required value={value.image} onChange={e=>onChange({...value,image:e.target.value})}/></label><label className="wide">Description<textarea required minLength="5" value={value.description} onChange={e=>onChange({...value,description:e.target.value})}/></label></div><div className="adm-check-row"><label><input type="checkbox" checked={Boolean(value.active)} onChange={e=>onChange({...value,active:e.target.checked})}/> Visible in store</label><label><input type="checkbox" checked={Boolean(value.featured)} onChange={e=>onChange({...value,featured:e.target.checked})}/> Featured</label></div><Button disabled={busy}>{busy?"Saving…":"Save product"}</Button></form>; }
function CouponForm({ value,onChange,onSubmit,busy }) { return <form className="adm-form" onSubmit={onSubmit}><div className="adm-form-grid"><label>Code<input required value={value.code} onChange={e=>onChange({...value,code:e.target.value.toUpperCase()})}/></label><label>Discount type<select value={value.discountType} onChange={e=>onChange({...value,discountType:e.target.value})}><option value="percent">Percentage</option><option value="fixed">Fixed amount</option></select></label><label>Discount value<input required type="number" min="1" value={value.discountValue} onChange={e=>onChange({...value,discountValue:e.target.value})}/></label><label>Minimum order<input type="number" min="0" value={value.minimumOrder} onChange={e=>onChange({...value,minimumOrder:e.target.value})}/></label><label>Usage limit<input type="number" min="1" value={value.usageLimit||""} onChange={e=>onChange({...value,usageLimit:e.target.value})}/></label><label>Starts<input type="datetime-local" value={value.startsAt?String(value.startsAt).slice(0,16):""} onChange={e=>onChange({...value,startsAt:e.target.value})}/></label><label>Expires<input type="datetime-local" value={value.expiresAt?String(value.expiresAt).slice(0,16):""} onChange={e=>onChange({...value,expiresAt:e.target.value})}/></label></div><label className="adm-check"><input type="checkbox" checked={Boolean(value.active)} onChange={e=>onChange({...value,active:e.target.checked})}/> Active campaign</label><Button disabled={busy}>{busy?"Saving…":"Save coupon"}</Button></form>; }

function Overview({ products,orders,customers,integrations,setView }) {
  const revenue=orders.filter(order=>order.status!=="cancelled").reduce((sum,order)=>sum+Number(order.total||0),0); const low=products.filter(product=>product.stock<10); const counts=["confirmed","processing","shipped","delivered"].map(status=>({status,count:orders.filter(order=>order.status===status).length})); const max=Math.max(1,...counts.map(item=>item.count));
  return <><div className="adm-page-head"><div><span>Operations overview</span><h1>Store performance</h1><p>Live operational signals from the BJ Electronics platform.</p></div><Button onClick={()=>setView("products")}><Plus/> Add product</Button></div><section className="adm-metrics"><article><span>Gross order value</span><strong>{money(revenue)}</strong><small><TrendUp/> Active order value</small></article><article><span>Total orders</span><strong>{orders.length}</strong><small><Package/> {orders.filter(o=>!["delivered","cancelled"].includes(o.status)).length} open</small></article><article><span>Catalog products</span><strong>{products.length}</strong><small><Cube/> {low.length} low stock</small></article><article><span>Customers</span><strong>{customers.length}</strong><small><UsersThree/> Registered accounts</small></article></section><div className="adm-overview-grid"><section className="adm-card adm-chart"><header><div><span>Fulfillment</span><h2>Order pipeline</h2></div><ChartBar/></header><div className="adm-bars">{counts.map(item=><div key={item.status}><span>{item.status}</span><div><i style={{height:`${Math.max(8,item.count/max*100)}%`}}/></div><strong>{item.count}</strong></div>)}</div></section><section className="adm-card"><header><div><span>Platform status</span><h2>Integrations</h2></div><Activity/></header><div className="adm-health"><div><span><CheckCircle/> Database</span><Status value="ok"/></div><div><span><CloudArrowUp/> Cloudinary</span><Status value={integrations.cloudinary?.status||"disabled"}/></div><div><span><Activity/> Redis</span><Status value={integrations.redis?.status||"disabled"}/></div></div></section><section className="adm-card adm-recent"><header><div><span>Fulfillment</span><h2>Recent orders</h2></div><button onClick={()=>setView("orders")}>View all <CaretRight/></button></header>{orders.slice(0,6).map(order=><article key={order.id}><Package/><div><strong>{order.orderNumber}</strong><small>{order.customerName} · {formatDate(order.createdAt)}</small></div><b>{money(order.total,order.currency)}</b><Status value={order.status}/></article>)}</section><section className="adm-card adm-stock"><header><div><span>Inventory</span><h2>Stock attention</h2></div><button onClick={()=>setView("inventory")}>Manage <CaretRight/></button></header>{low.slice(0,6).map(product=><article key={product.id}><img src={product.image} alt=""/><div><strong>{product.name}</strong><small>{product.sku}</small></div><b>{product.stock} left</b></article>)}{!low.length&&<Empty icon={CheckCircle} title="Inventory healthy" text="No products are below the low-stock threshold."/>}</section></div></>;
}

function Orders({ orders,saveStatus }) { const [query,setQuery]=useState(""); const [filter,setFilter]=useState("all"); const [selected,setSelected]=useState(null); const [busy,setBusy]=useState(false); const visible=orders.filter(order=>(filter==="all"||order.status===filter)&&`${order.orderNumber} ${order.customerName} ${order.customerPhone}`.toLowerCase().includes(query.toLowerCase())); const update=async(status)=>{setBusy(true);try{const order=await saveStatus(selected.id,status);setSelected(order);}finally{setBusy(false);}}; return <><div className="adm-page-head"><div><span>Order management</span><h1>Orders</h1><p>Search, inspect and update fulfillment status.</p></div></div><section className="adm-card adm-table-card"><div className="adm-toolbar"><label><MagnifyingGlass/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search orders"/></label><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All statuses</option><option value="confirmed">Confirmed</option><option value="processing">Processing</option><option value="shipped">Shipped</option><option value="delivered">Delivered</option><option value="cancelled">Cancelled</option></select></div><div className="adm-table"><div className="adm-tr head"><span>Order</span><span>Customer</span><span>Date</span><span>Total</span><span>Status</span><span/></div>{visible.map(order=><button className="adm-tr" key={order.id} onClick={()=>setSelected(order)}><span><strong>{order.orderNumber}</strong><small>{order.paymentMethod?.replaceAll("_"," ")}</small></span><span><strong>{order.customerName}</strong><small>{order.customerPhone}</small></span><span>{formatDate(order.createdAt)}</span><strong>{money(order.total,order.currency)}</strong><Status value={order.status}/><CaretRight/></button>)}</div>{!visible.length&&<Empty title="No matching orders" text="Change the search or status filter."/>}</section><Drawer open={Boolean(selected)} title={selected?.orderNumber||"Order"} onClose={()=>setSelected(null)}><div className="adm-order-detail"><Status value={selected?.status}/><dl><div><dt>Customer</dt><dd>{selected?.customerName}</dd></div><div><dt>Phone</dt><dd>{selected?.customerPhone}</dd></div><div><dt>Total</dt><dd>{money(selected?.total,selected?.currency)}</dd></div><div><dt>Payment</dt><dd>{selected?.paymentMethod?.replaceAll("_"," ")}</dd></div><div><dt>Address</dt><dd>{selected?.shippingAddress}</dd></div></dl><label>Fulfillment status<select value={selected?.status||"confirmed"} onChange={e=>update(e.target.value)} disabled={busy}><option value="confirmed">Confirmed</option><option value="processing">Processing</option><option value="shipped">Shipped</option><option value="delivered">Delivered</option><option value="cancelled">Cancelled</option></select></label></div></Drawer></>;
}

function Products({ products,saveProduct,inventoryOnly=false }) { const [query,setQuery]=useState(""); const [editing,setEditing]=useState(null); const [draft,setDraft]=useState(EMPTY_PRODUCT); const [busy,setBusy]=useState(false); const visible=products.filter(product=>`${product.name} ${product.sku} ${product.category} ${product.brand||""}`.toLowerCase().includes(query.toLowerCase())).filter(product=>!inventoryOnly||product.stock<20); const open=(product=null)=>{setEditing(product||{});setDraft(product?{...product,price:String(product.price),oldPrice:product.oldPrice?String(product.oldPrice):"",stock:String(product.stock)}:EMPTY_PRODUCT);}; const submit=async(event)=>{event.preventDefault();setBusy(true);try{await saveProduct(editing?.id,{...draft,price:Number(draft.price),oldPrice:draft.oldPrice?Number(draft.oldPrice):null,stock:Number(draft.stock),subcategory:draft.subcategory||null,brand:draft.brand||null,sourceName:draft.sourceName||null,sourceUrl:draft.sourceUrl||null});setEditing(null);}finally{setBusy(false);}}; return <><div className="adm-page-head"><div><span>{inventoryOnly?"Stock control":"Catalog management"}</span><h1>{inventoryOnly?"Inventory":"Products"}</h1><p>{inventoryOnly?"Products below 20 units are shown first.":"Create, edit and publish store products."}</p></div>{!inventoryOnly&&<Button onClick={()=>open()}><Plus/> Add product</Button>}</div><section className="adm-card adm-table-card"><div className="adm-toolbar"><label><MagnifyingGlass/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products"/></label><span>{visible.length} products</span></div><div className="adm-products"><div className="adm-product-row head"><span>Product</span><span>Price</span><span>Stock</span><span>Visibility</span><span/></div>{visible.map(product=><div className="adm-product-row" key={product.id}><div><img src={product.image} alt=""/><span><strong>{product.name}</strong><small>{product.sku} · {product.category}</small></span></div><strong>{money(product.price,product.currency)}</strong><div className="adm-stock-controls"><button aria-label={`Decrease ${product.name} stock`} onClick={()=>saveProduct(product.id,{stock:Math.max(0,product.stock-1)})}>−</button><b>{product.stock}</b><button aria-label={`Increase ${product.name} stock`} onClick={()=>saveProduct(product.id,{stock:product.stock+1})}>+</button></div><button className={`adm-toggle ${product.active?"active":""}`} onClick={()=>saveProduct(product.id,{active:!product.active})}>{product.active?"Active":"Hidden"}</button><IconButton label={`Edit ${product.name}`} onClick={()=>open(product)}><PencilSimple/></IconButton></div>)}</div>{!visible.length&&<Empty icon={Cube} title="No matching products" text="Change the search or stock filter."/>}</section><Drawer open={Boolean(editing)} title={editing?.id?"Edit product":"Add product"} onClose={()=>setEditing(null)} wide><ProductForm value={draft} onChange={setDraft} onSubmit={submit} busy={busy}/></Drawer></>;
}

function Customers({ customers }) { const [query,setQuery]=useState(""); const [selected,setSelected]=useState(null); const visible=customers.filter(customer=>`${customer.name} ${customer.email} ${customer.phone||""}`.toLowerCase().includes(query.toLowerCase())); return <><div className="adm-page-head"><div><span>Customer relationships</span><h1>Customers</h1><p>Account activity and lifetime order value.</p></div></div><section className="adm-card adm-table-card"><div className="adm-toolbar"><label><MagnifyingGlass/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search customers"/></label><span>{visible.length} accounts</span></div><div className="adm-customers"><div className="adm-customer-row head"><span>Customer</span><span>Contact</span><span>Orders</span><span>Lifetime value</span><span>Joined</span><span/></div>{visible.map(customer=><button className="adm-customer-row" key={customer.id} onClick={()=>setSelected(customer)}><span className="adm-avatar"><i>{customer.name.split(" ").map(part=>part[0]).slice(0,2).join("")}</i><strong>{customer.name}</strong></span><span><strong>{customer.email}</strong><small>{customer.phone||"No phone"}</small></span><b>{customer.orderCount}</b><b>{money(customer.lifetimeValue)}</b><span>{formatDate(customer.createdAt)}</span><CaretRight/></button>)}</div></section><Drawer open={Boolean(selected)} title="Customer details" onClose={()=>setSelected(null)}><div className="adm-customer-detail"><div className="adm-large-avatar">{selected?.name.split(" ").map(part=>part[0]).slice(0,2).join("")}</div><h2>{selected?.name}</h2><a href={`mailto:${selected?.email}`}>{selected?.email}</a>{selected?.phone&&<a href={`tel:${selected.phone}`}>{selected.phone}</a>}<dl><div><dt>Orders</dt><dd>{selected?.orderCount}</dd></div><div><dt>Lifetime value</dt><dd>{money(selected?.lifetimeValue)}</dd></div><div><dt>Joined</dt><dd>{formatDate(selected?.createdAt)}</dd></div></dl></div></Drawer></>;
}

function Promotions({ coupons,saveCoupon }) { const [editing,setEditing]=useState(null); const [draft,setDraft]=useState(EMPTY_COUPON); const [busy,setBusy]=useState(false); const open=(coupon=null)=>{setEditing(coupon||{});setDraft(coupon?{...coupon,discountValue:String(coupon.discountValue),minimumOrder:String(coupon.minimumOrder),usageLimit:coupon.usageLimit?String(coupon.usageLimit):""}:EMPTY_COUPON);}; const submit=async(event)=>{event.preventDefault();setBusy(true);try{await saveCoupon(editing?.id,{...draft,discountValue:Number(draft.discountValue),minimumOrder:Number(draft.minimumOrder),usageLimit:draft.usageLimit?Number(draft.usageLimit):null,startsAt:draft.startsAt?new Date(draft.startsAt).toISOString():null,expiresAt:draft.expiresAt?new Date(draft.expiresAt).toISOString():null});setEditing(null);}finally{setBusy(false);}}; return <><div className="adm-page-head"><div><span>Campaign management</span><h1>Promotions</h1><p>Create and manage customer coupon offers.</p></div><Button onClick={()=>open()}><Plus/> New coupon</Button></div><div className="adm-coupon-grid">{coupons.map(coupon=><article className="adm-card" key={coupon.id}><header><div><Tag/><span><strong>{coupon.code}</strong><small>{coupon.discountType==="percent"?`${coupon.discountValue}% off`:money(coupon.discountValue)}</small></span></div><Status value={coupon.active?"active":"paused"}/></header><dl><div><dt>Minimum order</dt><dd>{money(coupon.minimumOrder)}</dd></div><div><dt>Used</dt><dd>{coupon.usedCount}{coupon.usageLimit?` / ${coupon.usageLimit}`:""}</dd></div><div><dt>Expires</dt><dd>{coupon.expiresAt?formatDate(coupon.expiresAt):"No expiry"}</dd></div></dl><div><Button variant="secondary" onClick={()=>open(coupon)}><PencilSimple/> Edit</Button><Button variant={coupon.active?"danger":"secondary"} onClick={()=>saveCoupon(coupon.id,{active:!coupon.active})}>{coupon.active?"Pause":"Activate"}</Button></div></article>)}{!coupons.length&&<Empty icon={Tag} title="No coupons" text="Create the first promotional campaign." action={<Button onClick={()=>open()}>Create coupon</Button>}/>}</div><Drawer open={Boolean(editing)} title={editing?.id?"Edit coupon":"Create coupon"} onClose={()=>setEditing(null)}><CouponForm value={draft} onChange={setDraft} onSubmit={submit} busy={busy}/></Drawer></>;
}

function Settings({ integrations }) { return <><div className="adm-page-head"><div><span>Platform configuration</span><h1>Settings and health</h1><p>Production routes, integrations and security boundaries.</p></div></div><div className="adm-settings"><section className="adm-card"><header><div><span>Production routes</span><h2>Application surfaces</h2></div><Storefront/></header><div className="adm-setting-list"><div><span>Storefront</span><strong>https://bjelectronics.shop/</strong></div><div><span>Administrator</span><strong>https://bjelectronics.shop/admin/</strong></div><div><span>API</span><strong>https://bjelectronics.shop/api/</strong></div></div></section><section className="adm-card"><header><div><span>External services</span><h2>Integration state</h2></div><Activity/></header><div className="adm-health"><div><span><Activity/> Redis catalog cache</span><Status value={integrations.redis?.status||"disabled"}/></div><div><span><CloudArrowUp/> Cloudinary media</span><Status value={integrations.cloudinary?.status||"disabled"}/></div></div></section><section className="adm-card"><header><div><span>Access controls</span><h2>Administrator security</h2></div><ShieldCheck/></header><ul className="adm-security"><li><CheckCircle/> Dedicated HTTP-only administrator cookie</li><li><CheckCircle/> Two-hour administrator session</li><li><CheckCircle/> Role checks on every administrator API</li><li><CheckCircle/> CSRF protection for write operations</li><li><CheckCircle/> Private, no-store administrator responses</li></ul></section><section className="adm-card"><header><div><span>Deployment</span><h2>Hostinger auto deployment</h2></div><Truck/></header><p>Successful merges to the connected <code>main</code> branch trigger the Hostinger build. Production uses <code>npm run hostinger:build</code>, output directory <code>dist</code> and entry file <code>index.js</code>.</p><a href="/api/health" target="_blank" rel="noreferrer">Open API health <ArrowRight/></a></section></div></>;
}

function Sidebar({ active,setActive,open,setOpen,user,onLogout }) { return <aside className={`adm-sidebar ${open?"open":""}`}><div className="adm-brand"><img src="/assets/bj-logo.png" alt="BJ Electronics"/><span><strong>BJ Admin</strong><small>Operations center</small></span><IconButton label="Close navigation" onClick={()=>setOpen(false)}><X/></IconButton></div><nav>{NAV.map(([id,Icon,label])=><button key={id} className={active===id?"active":""} onClick={()=>{setActive(id);setOpen(false);window.history.replaceState({},"",`/admin/${id==="overview"?"dashboard":id}`);}}><Icon weight={active===id?"fill":"regular"}/><span>{label}</span><CaretRight/></button>)}</nav><div className="adm-sidebar-user"><UserCircle/><span><strong>{user.name}</strong><small>Administrator</small></span><IconButton label="Sign out" onClick={onLogout}><SignOut/></IconButton></div></aside>; }
function Topbar({ title,user,onMenu,theme,setTheme,search,setSearch }) { return <header className="adm-topbar"><IconButton label="Open navigation" onClick={onMenu}><List/></IconButton><div><span>Administrator workspace</span><h1>{title}</h1></div><label className="adm-global-search"><MagnifyingGlass/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search current workspace" aria-label="Search current workspace"/></label><div className="adm-top-actions"><IconButton label={`Use ${theme==="light"?"dark":"light"} theme`} onClick={()=>setTheme(theme==="light"?"dark":"light")}>{theme==="light"?<Moon/>:<Sun/>}</IconButton><IconButton label="Notifications"><Bell/></IconButton><a href="/" target="_blank" rel="noreferrer" aria-label="Open storefront"><Storefront/></a><span>{user.name.split(" ").map(part=>part[0]).slice(0,2).join("")}</span></div></header>; }

function Workspace({ user,onLogout }) {
  const path=location.pathname.split("/")[2]; const initial={dashboard:"overview",orders:"orders",products:"products",inventory:"inventory",customers:"customers",promotions:"promotions",media:"media",settings:"settings"}[path]||"overview";
  const [view,setView]=useState(initial); const [mobile,setMobile]=useState(false); const [theme,setTheme]=useState(()=>readStorage("bj:admin-theme","light")); const [search,setSearch]=useState(""); const [products,setProducts]=useState([]); const [orders,setOrders]=useState([]); const [customers,setCustomers]=useState([]); const [coupons,setCoupons]=useState([]); const [integrations,setIntegrations]=useState({redis:{status:"checking"},cloudinary:{status:"checking"}}); const [loading,setLoading]=useState(true); const [toasts,setToasts]=useState([]);
  const notify=useCallback((message,tone="success")=>{const id=`${Date.now()}-${Math.random()}`;setToasts(items=>[...items,{id,message,tone}]);setTimeout(()=>setToasts(items=>items.filter(item=>item.id!==id)),4000);},[]);
  const request=useCallback((path,options)=>apiRequest(path,options),[]);
  const load=useCallback(async()=>{setLoading(true);try{const [p,o,c,cp,i]=await Promise.all([request("/api/admin/products"),request("/api/admin/orders"),request("/api/admin/customers"),request("/api/admin/coupons"),request("/api/admin/integrations")]);setProducts(p.products||[]);setOrders(o.orders||[]);setCustomers(c.customers||[]);setCoupons(cp.coupons||[]);setIntegrations(i);}catch(error){notify(error.message,"error");}finally{setLoading(false);}},[request,notify]); useEffect(()=>{load();},[load]); useEffect(()=>{document.documentElement.dataset.adminTheme=theme;writeStorage("bj:admin-theme",theme);},[theme]);
  const saveProduct=async(id,data)=>{try{const response=await request(id?`/api/admin/products/${id}`:"/api/admin/products",{method:id?"PATCH":"POST",body:data});setProducts(items=>id?items.map(item=>item.id===id?response.product:item):[response.product,...items]);notify(id?"Product updated.":"Product created.");return response.product;}catch(error){notify(error.message,"error");throw error;}};
  const saveStatus=async(id,status)=>{try{const response=await request(`/api/admin/orders/${id}/status`,{method:"PATCH",body:{status}});setOrders(items=>items.map(item=>item.id===id?response.order:item));notify("Order status updated.");return response.order;}catch(error){notify(error.message,"error");throw error;}};
  const saveCoupon=async(id,data)=>{try{const response=await request(id?`/api/admin/coupons/${id}`:"/api/admin/coupons",{method:id?"PATCH":"POST",body:data});setCoupons(items=>id?items.map(item=>item.id===id?response.coupon:item):[response.coupon,...items]);notify(id?"Coupon updated.":"Coupon created.");return response.coupon;}catch(error){notify(error.message,"error");throw error;}};
  const filteredProducts=search?products.filter(p=>`${p.name} ${p.sku} ${p.category}`.toLowerCase().includes(search.toLowerCase())):products; const filteredOrders=search?orders.filter(o=>`${o.orderNumber} ${o.customerName}`.toLowerCase().includes(search.toLowerCase())):orders; const titles=Object.fromEntries(NAV.map(([id,,label])=>[id,label]));
  let content; if(loading)content=<Loading/>; else if(view==="overview")content=<Overview products={products} orders={orders} customers={customers} integrations={integrations} setView={setView}/>; else if(view==="orders")content=<Orders orders={filteredOrders} saveStatus={saveStatus}/>; else if(view==="products")content=<Products products={filteredProducts} saveProduct={saveProduct}/>; else if(view==="inventory")content=<Products products={filteredProducts} saveProduct={saveProduct} inventoryOnly/>; else if(view==="customers")content=<Customers customers={customers}/>; else if(view==="promotions")content=<Promotions coupons={coupons} saveCoupon={saveCoupon}/>; else if(view==="media")content=<MediaManager adminRequest={request}/>; else content=<Settings integrations={integrations}/>;
  return <div className="adm-app"><Sidebar active={view} setActive={setView} open={mobile} setOpen={setMobile} user={user} onLogout={onLogout}/>{mobile&&<button className="adm-mobile-scrim" aria-label="Close navigation" onClick={()=>setMobile(false)}/>}<div className="adm-main"><Topbar title={titles[view]} user={user} onMenu={()=>setMobile(true)} theme={theme} setTheme={setTheme} search={search} setSearch={setSearch}/><main className="adm-content">{content}</main></div><Toasts items={toasts} dismiss={id=>setToasts(items=>items.filter(item=>item.id!==id))}/></div>;
}

export function AdminPortal() {
  const [user,setUser]=useState(null); const [loading,setLoading]=useState(true);
  useEffect(()=>{apiRequest("/api/admin/auth/me").then(response=>setUser(response.user)).catch(()=>setUser(null)).finally(()=>setLoading(false));},[]);
  useEffect(()=>{if(loading)return;const login=!user;const target=login?"/admin/login":location.pathname.startsWith("/admin/")&&location.pathname!=="/admin/login"?location.pathname:"/admin/dashboard";if(location.pathname!==target)history.replaceState({},"",target);document.title=login?"BJ Admin — Secure Sign In":"BJ Admin — Operations Center";},[user,loading]);
  const logout=async()=>{try{await apiRequest("/api/admin/auth/logout",{method:"POST"});}finally{setUser(null);history.replaceState({},"","/admin/login");}};
  if(loading)return <Loading label="Securing administrator workspace"/>;
  return user?<Workspace user={user} onLogout={logout}/>:<Login onLogin={admin=>{setUser(admin);history.replaceState({},"","/admin/dashboard");}}/>;
}
